version: "3"

services:
    nginx:
        image: nginx:alpine
        ports:
        - "80:80"
        # Ensure the read and write access
        privileged: true
        volumes:
        - ./site/:/var/www/html/:rw
        - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
        - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./log/nginx/:/var/log/nginx/:rw

    mysql:
        image: mysql:5.7
        ports:
            - "10001:3306"
        privileged: true
        volumes:
            - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
            - ~/LuciDock/data:/var/lib/mysql/:rw
            - ./log/mysql/:/var/log/mysql/:rw
        environment:
            MYSQL_ROOT_PASSWORD: "123123"

    php53:
        build: ./php/php53/
        expose:
            - "9000"
        privileged: true
        volumes:
            - ./site/:/var/www/html:rw
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
            - ./log/php-fpm/:/var/log/php-fpm/:rw
        depends_on:
            - mysql

    php56:
        build: ./php/php56/
        expose:
            - "9000"
        privileged: true
        volumes:
            - ./site/:/var/www/html/:rw
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
            - ./log/php-fpm/:/var/log/php-fpm/:rw
        depends_on:
            - mysql

    php72:
        build: ./php/php72/
        expose:
            - "9000"
        privileged: true
        volumes:
            - ./site/:/var/www/html/:rw
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
            - ./log/php-fpm/:/var/log/php-fpm/:rw
        depends_on:
            - mysql

